POST http://localhost:3003/api/blogs/
Content-Type: application/json

{
    "title" : "Harry Potter and Friends",
    "author" : "Rowling",
    "url" : "https://hp.com" 
}

###
POST http://localhost:3003/api/users/
Content-Type: application/json

{
    "username": "testuser",
    "name": "Test User",
    "password": "te"
}